config/routes.rb
Rails.application.routes.draw do
  resources :profiles
  resources :skills do
    resources :requirements
  end
  root to: 'profiles#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/check.rb
class Check < ApplicationRecord
  belongs_to :profile
  belongs_to :requirement
end

app/models/profile.rb
class Profile < ApplicationRecord
  has_and_belongs_to_many :skills

  has_many :checks
  has_many :requirements, through: :checks
end

app/models/requirement.rb
class Requirement < ApplicationRecord
  belongs_to :skill
end

app/models/skill.rb
class Skill < ApplicationRecord
  has_and_belongs_to_many :profiles
  has_many :requirements

  accepts_nested_attributes_for :requirements, allow_destroy: true, reject_if: proc { |attributes| attributes['name'].blank? }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update, :destroy]

  # GET /profiles
  # GET /profiles.json
  def index
    @profiles = Profile.all
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
  end

  # GET /profiles/new
  def new
    @profile = Profile.new
  end

  # GET /profiles/1/edit
  def edit
    @skills = Skill.all.map {|skill| [skill.name.titleize, skill.id]}
    @selected_skill = params[:skill_id]
    # TODO: seleccionar los abilities correspondientes al skill seleccionado
    abilities = @profile.requirements
    if abilities.length > 0
      @abilities = abilities
    else
      current_skill = Skill.find(@selected_skill)
      @abilities = current_skill.requirements
    end
  end

  # POST /profiles
  # POST /profiles.json
  def create
    @profile = Profile.new(profile_params)

    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: 'Profile was successfully created.' }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to @profile, notice: 'Profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url, notice: 'Profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profile_params
      params.require(:profile).permit(:username, :about)
    end
end

app/controllers/requirements_controller.rb
class RequirementsController < ApplicationController
  before_action :set_requirement, only: [:show, :edit, :update, :destroy]

  # GET /requirements
  # GET /requirements.json
  def index
    @requirements = Requirement.all
  end

  # GET /requirements/1
  # GET /requirements/1.json
  def show
  end

  # GET /requirements/new
  def new
    @requirement = Requirement.new
  end

  # GET /requirements/1/edit
  def edit
  end

  # POST /requirements
  # POST /requirements.json
  def create
    @requirement = Requirement.new(requirement_params)

    respond_to do |format|
      if @requirement.save
        format.html { redirect_to @requirement, notice: 'Requirement was successfully created.' }
        format.json { render :show, status: :created, location: @requirement }
      else
        format.html { render :new }
        format.json { render json: @requirement.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /requirements/1
  # PATCH/PUT /requirements/1.json
  def update
    respond_to do |format|
      if @requirement.update(requirement_params)
        format.html { redirect_to @requirement, notice: 'Requirement was successfully updated.' }
        format.json { render :show, status: :ok, location: @requirement }
      else
        format.html { render :edit }
        format.json { render json: @requirement.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /requirements/1
  # DELETE /requirements/1.json
  def destroy
    @requirement.destroy
    respond_to do |format|
      format.html { redirect_to skill_requirements_url, notice: 'Requirement was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_requirement
      @requirement = Requirement.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def requirement_params
      params.require(:requirement).permit(:name, :skill_id)
    end
end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController
  before_action :set_skill, only: [:show, :edit, :update, :destroy]

  # GET /skills
  # GET /skills.json
  def index
    @skills = Skill.all
  end

  # GET /skills/1
  # GET /skills/1.json
  def show
  end

  # GET /skills/new
  def new
    @skill = Skill.new
  end

  # GET /skills/1/edit
  def edit
  end

  # POST /skills
  # POST /skills.json
  def create
    @skill = Skill.new(skill_params)

    respond_to do |format|
      if @skill.save
        format.html { redirect_to @skill, notice: 'Skill was successfully created.' }
        format.json { render :show, status: :created, location: @skill }
      else
        format.html { render :new }
        format.json { render json: @skill.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /skills/1
  # PATCH/PUT /skills/1.json
  def update
    respond_to do |format|
      if @skill.update(skill_params)
        # format.html { redirect_to @skill, notice: 'Skill was successfully updated.' }
        format.html { redirect_to edit_skill_url(@skill), notice: 'Skill was successfully updated.' }
        format.json { render :show, status: :ok, location: @skill }
      else
        format.html { render :edit }
        format.json { render json: @skill.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /skills/1
  # DELETE /skills/1.json
  def destroy
    @skill.destroy
    respond_to do |format|
      format.html { redirect_to skills_url, notice: 'Skill was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_skill
      @skill = Skill.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def skill_params
      params.require(:skill).permit(:name, requirements_attributes:[:name])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/requirements_helper.rb
module RequirementsHelper
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SelectMvc</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/profiles/_edit_form.html.haml
= form_for @profile do |f|
  - if @profile.errors.any?
    #error_explanation
    %h2= "#{pluralize(@profile.errors.count, "error")} prohibited this profile from being saved:"
    %ul
      - @profile.errors.full_messages.each do |message|
        %li= message
  
  .field
    = f.label :username
    = f.text_field :username
  .field
    = f.label :about
    = f.text_area :about
  .actions
    = f.submit 'Save'

%h2 Add some skills
= form_tag edit_profile_path, method: :get do
  .field
    = label_tag :skill #, "Choose a skill:"
    = label_tag :skill, "Select a skill:"
    = select_tag(:skill_id, options_for_select( @skills, @selected_skill ), {prompt: 'Pick a skill', onchange: 'this.form.submit();'})
    = collection_check_boxes(:requirements, :requirement_ids, @abilities, :id, :name)
%h2 Add some skills
= form_with model: @profile do |f|
  .field
    = f.label :skill, "Pick a skill:"
    = f.select(:skill_id, Skill.all.map {|skill| [skill.name.titleize, skill.id]}, {selected: @selected_skill, include_blank:  'Pick a skill'}, {onchange: 'this.form.submit();'})
    = f.collection_check_boxes(:requirement_ids, @abilities, :id, :name)
      
-# = form_for @profile do |f|

-#     .field
-#       = f.label :skill
-#       = f.
-#     .field
-#       = f.label :about
-#       = f.text_area :about
-#     .actions
-#       = f.submit 'Add'

app/views/profiles/_form.html.haml
= form_for @profile do |f|
  - if @profile.errors.any?
    #error_explanation
      %h2= "#{pluralize(@profile.errors.count, "error")} prohibited this profile from being saved:"
      %ul
        - @profile.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :username
    = f.text_field :username
  .field
    = f.label :about
    = f.text_area :about
  .actions
    = f.submit 'Save'

app/views/profiles/edit.html.haml
%h1 Editing profile

= render 'edit_form'

= link_to 'Show', @profile
\|
= link_to 'Back', profiles_path

app/views/profiles/index.html.haml
%h1 Listing profiles

%table
  %thead
    %tr
      %th Username
      %th About
      %th
      %th
      %th

  %tbody
    - @profiles.each do |profile|
      %tr
        %td= profile.username
        %td= profile.about
        %td= link_to 'Show', profile
        %td= link_to 'Edit', edit_profile_path(profile)
        %td= link_to 'Destroy', profile, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Profile', new_profile_path

app/views/profiles/new.html.haml
%h1 New profile

= render 'form'

= link_to 'Back', profiles_path

app/views/profiles/show.html.haml
%p#notice= notice

%p
  %b Username:
  = @profile.username
  %b About:
  = @profile.about

= link_to 'Edit', edit_profile_path(@profile)
\|
= link_to 'Back', profiles_path

app/views/requirements/_form.html.haml
= form_for @requirement do |f|
  - if @requirement.errors.any?
    #error_explanation
      %h2= "#{pluralize(@requirement.errors.count, "error")} prohibited this requirement from being saved:"
      %ul
        - @requirement.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :skill
    = f.text_field :skill
  .actions
    = f.submit 'Save'

app/views/requirements/edit.html.haml
%h1 Editing requirement

= render 'form'

= link_to 'Show', @requirement
\|
= link_to 'Back', requirements_path

app/views/requirements/index.html.haml
%h1 Listing requirements

%table
  %thead
    %tr
      %th Name
      %th Skill
      %th
      %th
      %th

  %tbody
    - @requirements.each do |requirement|
      %tr
        %td= requirement.name
        %td= requirement.skill.name
        %td= link_to 'Show', skill_requirement_path(requirement.skill, requirement)
        %td= link_to 'Edit', edit_skill_requirement_path(requirement.skill, requirement)
        %td= link_to 'Destroy', skill_requirement_path(requirement.skill, requirement), method: :delete, data: { confirm: 'Are you sure?' }

%br

-# = link_to 'New Requirement', new_skill_requirement_path(requirement.skill)

app/views/requirements/new.html.haml
%h1 New requirement

= render 'form'

= link_to 'Back', requirements_path

app/views/requirements/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @requirement.name
%p
  %b Skill:
  = @requirement.skill

= link_to 'Edit', edit_requirement_path(@requirement)
\|
= link_to 'Back', requirements_path

app/views/skills/_edit_form.html.haml
= form_for @skill do |f|
  - if @skill.errors.any?
    #error_explanation
      %h2= "#{pluralize(@skill.errors.count, "error")} prohibited this skill from being saved:"
      %ul
        - @skill.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :name
    = f.text_field :name
    
  %h2 New concept
  = f.fields_for :requirements, Requirement.new do |ff|
    .field
      = ff.label :name
      = ff.text_field :name
  .actions
    = f.submit 'Save'

%h2 Concepts
- @skill.requirements.each do |concept|
  .concept
    = "| #{concept.name} |"

app/views/skills/_form.html.haml
= form_for @skill do |f|
  - if @skill.errors.any?
    #error_explanation
      %h2= "#{pluralize(@skill.errors.count, "error")} prohibited this skill from being saved:"
      %ul
        - @skill.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :name
    = f.text_field :name
  .actions
    = f.submit 'Save'

app/views/skills/edit.html.haml
%p#notice= notice

%h1 Editing skill

= render 'edit_form'

= link_to 'Show', @skill
\|
= link_to 'Back', skills_path

app/views/skills/index.html.haml
%h1 Listing skills

%table
  %thead
    %tr
      %th Name
      %th
      %th
      %th

  %tbody
    - @skills.each do |skill|
      %tr
        %td= skill.name
        %td= link_to 'Show', skill
        %td= link_to 'Edit', edit_skill_path(skill)
        %td= link_to 'Destroy', skill, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Skill', new_skill_path

app/views/skills/new.html.haml
%h1 New skill

= render 'form'

= link_to 'Back', skills_path

app/views/skills/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @skill.name

= link_to 'Edit', edit_skill_path(@skill)
\|
= link_to 'Back', skills_path